import { CourseLayout } from '@/components/course-layout'
import type { Unit } from '@/components/course-layout'

const units: Unit[] = [
  {
    number: 1,
    title: 'the living world: ecosystems',
    examWeight: '6–8%',
    topics: [
      'energy transfer & trophic levels',
      'food chains & food webs',
      'trophic levels & 10% rule',
      'primary productivity',
      'terrestrial vs aquatic biomes',
      'biogeochemical cycles',
      'ecological succession',
    ],
  },
  {
    number: 2,
    title: 'the living world: biodiversity',
    examWeight: '6–8%',
    topics: [
      'ecosystem diversity',
      'ecosystem services',
      'natural disruptions',
      'species diversity',
      'genetic diversity',
      'island biogeography',
      'ecological tolerance',
      'invasive species',
      'habitat fragmentation',
      'endangered species',
    ],
  },
  {
    number: 3,
    title: 'populations',
    examWeight: '10–15%',
    topics: [
      'carrying capacity',
      'population growth models',
      'r-selected vs K-selected',
      'generalist vs specialist',
      'survivorship curves',
      'age-structure diagrams',
      'demographic transition model',
      'human population growth',
    ],
  },
  {
    number: 4,
    title: 'earth systems & resources',
    examWeight: '10–15%',
    topics: [
      'plate tectonics',
      'soil formation & erosion',
      'watersheds & aquifers',
      'atmospheric layers',
      'global wind patterns',
      'geography & climate',
      'el niño & la niña',
      'thermal inversion',
      'ocean currents',
    ],
  },
  {
    number: 5,
    title: 'land & water use',
    examWeight: '10–15%',
    topics: [
      'tragedy of the commons',
      'green revolution',
      'pest control methods',
      'meat production & CAFOs',
      'aquaculture',
      'sustainable agriculture',
      'deforestation',
      'clear-cutting vs selective cutting',
      'urbanization',
      'aquifer depletion',
      'dams, levees & desalination',
      'mining',
    ],
  },
  {
    number: 6,
    title: 'energy resources & consumption',
    examWeight: '10–15%',
    topics: [
      'fossil fuels',
      'global energy use',
      'solar energy',
      'wind energy',
      'hydroelectric power',
      'geothermal energy',
      'biofuels & ethanol',
      'nuclear energy',
      'energy efficiency',
      'cogeneration',
    ],
  },
  {
    number: 7,
    title: 'atmospheric pollution',
    examWeight: '7–10%',
    topics: [
      'primary pollutants',
      'secondary pollutants',
      'photochemical vs industrial smog',
      'thermal inversions',
      'acid rain',
      'ozone depletion',
      'noise pollution',
      'reducing air pollution',
      'indoor air pollution',
    ],
  },
  {
    number: 8,
    title: 'aquatic & terrestrial pollution',
    examWeight: '7–10%',
    topics: [
      'water pollution sources',
      'thermal pollution',
      'eutrophication',
      'bioaccumulation & biomagnification',
      'pathogens & disease',
      'sewage treatment',
      'solid waste & landfills',
      'incineration & hazardous waste',
      'oil spills',
      'plastic pollution',
    ],
  },
  {
    number: 9,
    title: 'global change',
    examWeight: '15–20%',
    topics: [
      'greenhouse effect',
      'carbon cycle & feedbacks',
      'ocean warming & acidification',
      'sea level rise',
      'climate impacts on biodiversity',
      'climate tipping points',
      'mitigation strategies',
      'climate treaties',
      'carbon footprint',
      'environmental laws',
      'apes formulas',
      'frq practice',
    ],
  },
]

export default function APESPage() {
  return (
    <CourseLayout
      course={{
        id: 'apes',
        label: 'ap environmental science',
        short: 'apes',
        description: 'the interdisciplinary study of Earth\'s systems, human impacts, and solutions. master every ecosystem, cycle, and crisis for a 5.',
        banner: '/images/enviro-banner.jpg',
        accent: '#22c55e',
        accentLight: '#86efac',
        bgClass: 'bg-enviro-green',
        examDate: 'May 15, 2025 — morning session (8:00 AM ET)',
        units,
      }}
      basePath="/apes"
    />
  )
}
