import { CourseLayout } from '@/components/course-layout'
import type { Unit } from '@/components/course-layout'

const units: Unit[] = [
  {
    number: 1,
    title: 'period 1: 1491–1607',
    examWeight: '4–6%',
    topics: [
      'native american societies',
      'european exploration motives',
      'columbian exchange',
      'spanish colonization',
      'labor & caste systems',
      'african slavery beginnings',
      'native-european-african interactions',
    ],
  },
  {
    number: 2,
    title: 'period 2: 1607–1754',
    examWeight: '6–8%',
    topics: [
      'jamestown & virginia',
      'bacon\'s rebellion',
      'plymouth & massachusetts bay',
      'salem witch trials',
      'new england colonies',
      'chesapeake & southern colonies',
      'middle colonies',
      'representative government',
      'mercantilism & salutary neglect',
      'enlightenment ideas',
      'first great awakening',
      'transatlantic trade & slavery',
    ],
  },
  {
    number: 3,
    title: 'period 3: 1754–1800',
    examWeight: '10–17%',
    topics: [
      'french & indian war',
      'proclamation of 1763',
      'taxation without representation',
      'boston massacre & tea party',
      'intolerable acts & continental congress',
      'declaration of independence',
      'revolutionary war & treaty of paris',
      'republican motherhood',
      'articles of confederation',
      'northwest ordinance',
      'constitutional convention',
      'federalists vs anti-federalists',
      'washington & hamilton\'s financial plan',
      'whiskey rebellion',
      'alien & sedition acts',
      'first party system',
    ],
  },
  {
    number: 4,
    title: 'period 4: 1800–1848',
    examWeight: '10–17%',
    topics: [
      'jefferson presidency',
      'marshall court decisions',
      'louisiana purchase',
      'war of 1812',
      'era of good feelings',
      'missouri compromise',
      'monroe doctrine',
      'market revolution',
      'rise of sectionalism',
      'jacksonian democracy',
      'nullification crisis',
      'indian removal act',
      'second great awakening',
      'abolitionism',
      'women\'s rights & seneca falls',
      'transcendentalism',
    ],
  },
  {
    number: 5,
    title: 'period 5: 1844–1877',
    examWeight: '10–17%',
    topics: [
      'manifest destiny',
      'mexican-american war',
      'compromise of 1850',
      'fugitive slave act',
      'underground railroad',
      'uncle tom\'s cabin',
      'kansas-nebraska act',
      'dred scott decision',
      'election of 1860',
      'civil war turning points',
      'emancipation proclamation',
      'reconstruction plans',
      'black codes & sharecropping',
      '13th, 14th & 15th amendments',
      'compromise of 1877',
    ],
  },
  {
    number: 6,
    title: 'period 6: 1865–1898',
    examWeight: '10–17%',
    topics: [
      'industrialization & railroads',
      'big business & social darwinism',
      'labor unions',
      'new immigration',
      'chinese exclusion act',
      'urbanization',
      'political machines',
      'gilded age politics',
      'dawes act',
      'sherman antitrust act',
      'populist movement',
    ],
  },
  {
    number: 7,
    title: 'period 7: 1890–1945',
    examWeight: '10–17%',
    topics: [
      'muckrakers',
      'progressive era reforms',
      'spanish-american war',
      'american imperialism',
      'world war I',
      'first red scare',
      'roaring twenties',
      'harlem renaissance',
      'immigration restrictions',
      'great depression',
      'new deal',
      'causes of wwii',
      'world war ii home front',
      'japanese american internment',
      'wwii turning points',
    ],
  },
  {
    number: 8,
    title: 'period 8: 1945–1980',
    examWeight: '10–17%',
    topics: [
      'cold war & containment',
      'mccarthyism & red scare',
      'korean war',
      'cuban missile crisis',
      'space race',
      'civil rights movement',
      'civil rights legislation',
      'great society',
      'vietnam war',
      'counterculture',
      'feminist movement',
      'environmental movement',
      'nixon & watergate',
      'conservative movement',
    ],
  },
  {
    number: 9,
    title: 'period 9: 1980–present',
    examWeight: '4–6%',
    topics: [
      'reagan revolution',
      'end of cold war',
      'globalization',
      'technology & internet',
      '9/11 & war on terror',
      'great recession',
      'affordable care act',
      'immigration debates',
      'modern social movements',
      'political polarization',
      'supreme court landmark cases',
      'dbq, leq & saq practice',
    ],
  },
]

export default function APUSHPage() {
  return (
    <CourseLayout
      course={{
        id: 'apush',
        label: 'ap united states history',
        short: 'apush',
        description: 'from 1491 to the present — every period, turning point, and essay strategy to lock in a 5.',
        banner: '/images/apush-banner.jpg',
        accent: '#ef4444',
        accentLight: '#f59e0b',
        bgClass: 'bg-apush-red',
        examDate: 'May 8, 2025 — morning session (8:00 AM ET)',
        units,
      }}
      basePath="/apush"
    />
  )
}
